{{- if .Values.cansoAirflowJobs.enabled }}
{{- if .Values.external_secret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.external_secret.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: {{ .Values.external_secret.clusterSecretRole }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.external_secret.targetName }}
    template:
      type: {{ .Values.external_secret.targetType }}
  data:
  - secretKey: {{ .Values.external_secret.secretKey }}
    remoteRef:
      key: {{ .Values.external_secret.remoteRefKey }}
      property: {{ .Values.external_secret.remoteRefProperty }}
{{- end }}
{{- end }}