{{- if .Values.cansoAirflowJobs.enabled }}
{{- if .Values.podRoleBinding.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.podRoleBinding.name }}
  namespace: {{ .Values.namespace.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.podRole.name }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.podRoleBinding.serviceAccount_name }}
  namespace: {{ .Values.airflowNamespace }}
{{- end }}
{{- end }}