{{- if .Values.cansoAirflowJobs.enabled }}
{{- if .Values.serviceAccount.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace.name }}
  annotations: 
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.role_arn }}
{{- end }}
{{- end }}