apiVersion: v2
name: canso-dplane-otelcollector
description: A Helm chart for deploying otelcollector in data plane
type: application
version: 0.0.2
appVersion: "0.0.1"

dependencies:
  - name: opentelemetry-collector
    version: "0.158.1"
    repository: "https://open-telemetry.github.io/opentelemetry-helm-charts"
