{{- if .Values.cansoAgent.enabled -}}
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: canso-agent
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  labels:
    canso.ai/product-component: "canso-apps"
    canso.ai/part-of: "superchart"
    canso.ai/infra-component: "dataplane-agents"
    canso.ai/infra-tag: "1002"
spec:
  generators:
  - list:
      elements:
      - cluster: {{ .Values.clusterName }}
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: canso-agent
    spec:
      project: {{ .Values.argocdProject }}
      destination:
        namespace: canso-dataplane
        server: https://kubernetes.default.svc
      source:
        repoURL: 'https://yugen-ai.github.io/canso-helm-charts'
        chart: canso-agent
        targetRevision: 0.1.8
        helm:
          values: |-
            config:
              tenantName: {{ .Values.tenantName }}
              tenantID: {{ .Values.tenantID }}
              queue_host: {{ .Values.queue_hostname }}
              queue_username: {{ .Values.queue_auth.username }}
              queue_password: {{ .Values.queue_auth.password_encoded }}  
              outgoing_queue: {{ .Values.queues.outgoing_queue }}
              incoming_queue: {{ .Values.queues.incoming_queue }}
            airflowDeploySecret:
              username: admin
              password: {{ .Values.airflow.user.password }}
            cansoAgent:
              enabled: true
              serviceAccount:
                create: true
                annotations:
                  eks.amazonaws.com/role-arn: {{ .Values.cansoAgent.roleArn }}
              {{- with .Values.cansoAgent.tolerations }}    
              tolerations:
                {{ toYaml . | nindent 12 }}
              {{- end }}
              {{- with .Values.cansoAgent.affinity }}
              affinity:
                {{ toYaml . | nindent 12 }}
              {{- end }}
              external_secret:
                enabled: true
                target_secret_name: {{ (index .Values.canso.imagePullSecrets 0).targetName }}
                target_secret_type: {{ (index .Values.canso.imagePullSecrets 0).targetType }}
                target_secret_name_key: {{ (index .Values.canso.imagePullSecrets 0).secretKey }}
                aws_secret_name: {{ (index .Values.canso.imagePullSecrets 0).remoteRefKey }}
                aws_secret_key: {{ (index .Values.canso.imagePullSecrets 0).remoteRefProperty }}
              secretStoreRef:
                name: {{ (index .Values.canso.imagePullSecrets 0).clusterSecretRole }}
                kind: ClusterSecretStore
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
{{- end }}