{{- if .Values.externalSecrets.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: external-secrets-setup
  namespace: kube-system
  annotations:
    # helm.sh/hook: post-install
    helm.sh/hook-weight: "-18"
    helm.sh/hook-delete-policy: hook-succeeded
spec:
  template:
    spec:
      serviceAccountName: argocd-manager
      containers:
        - name: kubectl
          image: bitnami/kubectl:latest
          command: ["sh", "-c"]
          args:
            - |
              # while ! kubectl get deployment -n external-secrets external-secrets-operator -o jsonpath='{.status.readyReplicas}' | grep -q 1; do
              echo "Waiting for external-secrets operator to be ready for 1 min..."
              sleep 60
              # done
              cat <<EOF | kubectl apply -f -

              ---

              apiVersion: 'external-secrets.io/v1beta1'
              kind: ClusterSecretStore
              metadata:
                name: secretstore-by-role
                labels:
                  canso.ai/product-component: "infra-dependencies"
                  canso.ai/part-of: "superchart"
                  canso.ai/infra-component: "external-secrets-sa"
                  canso.ai/infra-tag: "1000"
                  canso.ai/component-domain: "external-secrets-operator"
              spec:
                provider:
                  aws:
                    service: SecretsManager
                    region: {{ .Values.externalSecrets.clusterSecretStore.region }}
                    auth:
                      jwt:
                        serviceAccountRef:
                          name: {{ .Values.externalSecrets.serviceaccount.name }}
                          namespace: external-secrets

              ---
              
              {{- range .Values.canso.imagePullSecrets }}
              apiVersion: external-secrets.io/v1beta1
              kind: ExternalSecret
              metadata:
                name: {{ .name }}
                namespace: spark-streaming-jobs
              spec:
                refreshInterval: 1h
                secretStoreRef:
                  name: secretstore-by-role
                  kind: ClusterSecretStore
                target:
                  name: {{ .targetName }}
                data:
                  - secretKey: {{ .secretKey }}
                    remoteRef:
                      key: {{ .remoteRefKey }}
                      property: {{ .remoteRefProperty }}
              {{- end }}

              ---

              {{- range .Values.canso.imagePullSecrets }}
              apiVersion: external-secrets.io/v1beta1
              kind: ExternalSecret
              metadata:
                name: {{ .name }}
                namespace: spark-streaming-ml-jobs
              spec:
                refreshInterval: 1h
                secretStoreRef:
                  name: secretstore-by-role
                  kind: ClusterSecretStore
                target:
                  name: {{ .targetName }}
                data:
                  - secretKey: {{ .secretKey }}
                    remoteRef:
                      key: {{ .remoteRefKey }}
                      property: {{ .remoteRefProperty }}
              {{- end }}

              ---
              EOF
      restartPolicy: Never
{{- end }}
