{{- if .Values.grafana.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: grafana
  namespace: argocd
  labels:
    canso.ai/product-component: "infra-dependencies"
    canso.ai/part-of: "superchart"
    canso.ai/infra-component: "grafana"
    canso.ai/infra-tag: "1000"
spec:
  generators:
  - list:
      elements:
      - cluster: {{ .Values.clusterName }}
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: "grafana"
    spec:
      project: {{ .Values.argocdProject }}
      destination:
        server: https://kubernetes.default.svc
        namespace: grafana
      sources:
      - repoURL: 'https://grafana.github.io/helm-charts'
        #TODO Use the yugen platform helm chart for grafana and ingress ?
        targetRevision: "8.0.0"
        chart: grafana
        helm:
          releaseName: grafana
          values: |
            admin:
              existingSecret: ''
              passwordKey: admin-password
              userKey: admin-user
            adminPassword: {{ .Values.grafana.adminPassword }}
            adminUser:  {{ .Values.grafana.adminUser }}
            datasources:
              datasources.yaml:
                apiVersion: 1
                datasources:
                  - access: proxy
                    isDefault: true
                    name: Prometheus
                    type: prometheus
                    url: 'http://prometheus-server.prometheus.svc.cluster.local'
                  - access: proxy
                    isDefault: false
                    name: Loki
                    type: loki
                    url: 'http://loki.loki:3100'
            persistence:
              accessModes:
                - ReadWriteOnce
              enabled: true
              extraPvcLabels: {}
              inMemory:
                enabled: false
              size: {{ .Values.grafana.persistenceSize }}
              type: pvc
            serviceAccount:
              autoMount: true
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          #- ServerSideApply=true
  syncPolicy:
    preserveResourcesOnDeletion: true
{{- end}}