{{- if .Values.ingress.master.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nginx
  namespace: nginx-ingress 
  #TODO: update namespace from values.yaml appset installation
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-weight: "10"
    nginx.org/mergeable-ingress-type: "master"
    nginx.org/basic-auth-secret: "cred" 
    #TODO: Create Secret template in the above namespace after namespace creation
spec:
  ingressClassName: "nginx"
  rules:
  - host: '*.com'


{{- range .Values.ingress.services }}
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .serviceName }}-ing
  namespace: {{ .namespace }}
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-weight: "10"
    nginx.org/mergeable-ingress-type: "minion"
  {{- with .annotations }}
    {{- toYaml .| nindent 4 }}
  {{- end }}    
spec:
  ingressClassName: "nginx"  
  rules:
  - host: '{{ .host }}'
    http:
      paths:
      - path: {{ .path }}
        pathType: Prefix
        backend:
          service:
            name: {{ .serviceName }}
            port:
              number: {{ .servicePort }}

{{- end }}

{{- end }}

