{{- if .Values.karpenter.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: karpenter-setup-nodepools
  namespace: kube-system
  annotations:
    # helm.sh/hook: post-install
    helm.sh/hook-weight: "-18"
    helm.sh/hook-delete-policy: hook-succeeded
spec:
  template:
    spec:
      serviceAccountName: argocd-manager
      containers:
        - name: kubectl
          image: bitnami/kubectl:latest
          command: ["sh", "-c"]
          args:
            - |
              echo "Waiting for external-secrets operator to be ready for 1 min..."
              sleep 60
              # done
              cat <<EOF | kubectl apply -f -

              ---

              apiVersion: karpenter.sh/v1beta1
              kind: NodePool
              metadata:
                name: spot-ondemand-nodepool
              spec:
                template:
                  spec:
                    requirements:
                      - key: kubernetes.io/arch
                        operator: In
                        values: ["amd64"]
                      - key: kubernetes.io/os
                        operator: In
                        values: ["linux"]
                      - key: karpenter.sh/capacity-type
                        operator: In
                        values: ["spot","on-demand"]
                      - key: karpenter.k8s.aws/instance-category
                        operator: In
                        values: ["c", "m", "r","t"]
                      - key: karpenter.k8s.aws/instance-generation
                        operator: Gt
                        values: ["2"]
                    nodeClassRef:
                      name: spot-ondemand-nodeclass

                limits:
                  cpu: 1000
              ---

              apiVersion: karpenter.k8s.aws/v1beta1
              kind: EC2NodeClass
              metadata:
                name: spot-ondemand-nodeclass
              spec:
                amiFamily: AL2 # Amazon Linux 2
                role: {{ .Values.karpenter.nodeRoleArn}} 
                subnetSelectorTerms:
                  - tags:
                      karpenter.sh/discovery: {{ .Values.clusterName }} 
                securityGroupSelectorTerms:
                  - tags:
                      karpenter.sh/discovery: {{ .Values.clusterName }} 

              ---
              EOF
      restartPolicy: Never
{{- end }}