{{- if .Values.priorityClass.enabled }}
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ .Values.priorityClass.name }}
value: 1000000
globalDefault: false
description: "High priority for critical workloads"

{{- end }}
