apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: otelcollector-image-pull-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: secretstore-by-role
    kind: ClusterSecretStore
  target:
    name: otelcollector-image-pull-secret
  dataFrom:
  - secretKey: .dockerconfigjson
    remoteRef:
      key: {{ .Values.imagePullSecret.cloudProviderSecretName }} 
      property: {{ .Values.imagePullSecret.cloudProviderSecretKey }}