apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: otelcollector-rabbitmq-credentials
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: secretstore-by-role
    kind: ClusterSecretStore
  target:
    name: otelcollector-rabbitmq-credentials
  dataFrom:
  - extract: 
      key: {{ .Values.rabbitmq.cloudProviderSecretName }}