apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rabbitmq-credentials-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: secretstore-by-role
    kind: ClusterSecretStore
  target:
    name: rabbitmq-credentials-secret
  dataFrom:
  - extract: 
      key: {{ .Values.rabbitmq_credential_secret_name }}