## @section ArgoCD Configs
##

## @param argocdProject ArgoCD project name.
##
argocdProject: canso-appsets # WARNING: CRITICAL VALUE - DO NOT CHANGE

## @param createProject Create the ArgoCD project.
createProject: true

## @section ArgoCD AI Agent Configs
##

## @param argocdAIAgentProject ArgoCD AI Agent project name.
##
argocdAIAgentProject: canso-ai-agents # WARNING: CRITICAL VALUE - DO NOT CHANGE

## @param createAIAgentProject Create the ArgoCD AI Agent project.
createAIAgentProject: true

## @section ArgoCD Canso User Components Configs
##

## @param argocdCansoComponentsProject ArgoCD Canso Components project name.
##
argocdCansoComponentsProject: canso-user-components # WARNING: CRITICAL VALUE - DO NOT CHANGE

## @param createComponentsProject Create the ArgoCD Canso Components project.
createComponentsProject: true

####################################################
################# Default Configs
####################################################

## @section Default Configs
## @param clusterName Name of the AWS EKS cluster. 
##
clusterName: "" # THIS VALUE IS MANDATORY FOR CANSO SETUP
## @param clusterEndpoint Endpoint URL of the AWS EKS cluster.
##
clusterEndpoint: "" # THIS VALUE IS MANDATORY FOR CANSO SETUP
## @param tenantName Name Assigned to the Tenant
##
tenantName: "" # THIS VALUE IS MANDATORY FOR CANSO SETUP (Reach out to the Canso Team for value)
## @param tenantID Unique ID assigned to the Tenant
##
tenantID: "" # THIS VALUE IS MANDATORY FOR CANSO SETUP (Reach out to the Canso Team)
## @param awsRegion AWS Region of the cluster
##
awsRegion: "" # THIS VALUE IS MANDATORY

## @param encryption_enabled Enable Encryption
##
encryption_enabled: ""
## @param fernet_key Fernet decryption for encrypted RabbitMQ messages
##
fernet_key: "" # THIS VALUE IS MANDATORY

####################################################
############### Queue Configs
####################################################
## @param queue_hostname hostname for queue server
##
queue_hostname: "rabbitmq-amqp.canso.ai"

## @skip queue_auth queue authentication username and password
queue_auth:
  password_encoded: ""
  username: ""

## @skip queues names of queue.
queues:
  incoming_queue: ""
  outgoing_queue: ""

####################################################
############### Tolerations & Affinity
####################################################

## @param tolerations Tolerations for the deployment.
##
tolerations: {}

## @param affinity Affinity for the deployment.
affinity: {}

####################################################
############### Karpenter Configs
####################################################

## @section Karpenter Configs
karpenter:
  ## @param karpenter.enabled Flag to enable Karpenter.
  ##
  enabled: true
  ## @param karpenter.roleArn Role ARN for Karpenter.
  ##
  roleArn: "" # THIS VALUE IS MANDATORY
  # roleArn: eks.amazonaws.com/role-arn: arn:aws:iam::AWS_ACCOUNT_ID:role/IAM_ROLE_NAME
  ## @param karpenter.nodeRoleArn Role ARN for Karpenter node.
  ##
  nodeRoleArn: "" # THIS VALUE IS MANDATORY
  # nodeRoleArn: eks.amazonaws.com/role-arn: arn:aws:iam::AWS_ACCOUNT_ID:role/IAM_ROLE_NAME


####################################################
############### StatsD Configs (For Airflow)
####################################################

## @section StatsD Configs
statsd:
  ## @param statsd.enabled Flag to enable StatsD.
  ##
  enabled: true

####################################################
############### Canso Images Pull Secrets
####################################################

## @section Canso Image Pull Secrets
canso:
  ## @skip canso.imagePullSecrets Image pull secrets for Canso dataplane
  imagePullSecrets:
    - name: canso-image-pull-secrets
      secretKey: .dockerconfigjson # key of the kubernetes secret
      remoteRefKey: canso-dockerhub-credentials # name of AWS secret
      remoteRefProperty: dockerhub # key of the secret in secrets manager
      targetName: docker-secret-cred # name of kubernetes secret
      targetType: kubernetes.io/dockerconfigjson
      clusterSecretRole: secretstore-by-role # name of the ClusterSecret Role


####################################################
#################### Metrics Server
####################################################

## @section Metrics Server Configuration
metricsServer:
  ## @param metricsServer.enabled Flag to enable Metrics Server
  ##
  enabled: true


####################################################
##################### AWS Configs
####################################################

## @section AWS Configs
aws:
  ## @subsection awsEbsCsiDriver parameters
  awsEbsCsiDriver:
    ## @param aws.awsEbsCsiDriver.enabled Flag to enable AWS EBS CSI Driver.
    ##
    enabled: true
    ## @param aws.awsEbsCsiDriver.roleArn Role ARN for AWS EBS CSI Driver.
    ##
    roleArn: "" # THIS VALUE IS MANDATORY
    # roleArn: eks.amazonaws.com/role-arn: arn:aws:iam::AWS_ACCOUNT_ID:role/IAM_ROLE_NAME
    
  ## @subsection awsEfsCsiDriver parameters
  awsEfsCsiDriver:

    ## @param aws.awsEfsCsiDriver.enabled Flag to enable AWS EFS CSI Driver.
    ##
    enabled: true
    ## @param aws.awsEfsCsiDriver.roleArn Role ARN for AWS EFS CSI Driver.
    ##
    roleArn: "" # THIS VALUE IS MANDATORY
    # roleArn: eks.amazonaws.com/role-arn: arn:aws:iam::AWS_ACCOUNT_ID:role/IAM_ROLE_NAME
    
  ## @subsection awsLoadBalancerController parameters
  awsLoadBalancerController:
    ## @param aws.awsLoadBalancerController.enabled Flag to enable AWS Load Balancer Controller
    ##
    enabled: true
    ## @param aws.awsLoadBalancerController.roleArn Role ARN for AWS Load Balancer Controller
    ##
    roleArn: "" # THIS VALUE IS MANDATORY
    # roleArn: eks.amazonaws.com/role-arn: arn:aws:iam::AWS_ACCOUNT_ID:role/IAM_ROLE_NAME

  ## @subsection awsACK parameters
  awsACK:
    ## @param aws.awsACK.enabled Flag to enable AWS ACK
    ##
    enabled: true

####################################################
##################### External Secrets
####################################################

## @section External Secrets
externalSecrets:
  ## @param externalSecrets.enabled Flag to enable External Secrets
  ##
  enabled: true

  ## @subsection externalSecrets.serviceaccount parameters
  serviceaccount:
    ## @param externalSecrets.serviceaccount.roleArn arn Role ARN for External Secrets service account.
    ##
    roleArn: "" # THIS VALUE IS MANDATORY
    # roleArn: eks.amazonaws.com/role-arn: arn:aws:iam::AWS_ACCOUNT_ID:role/IAM_ROLE_NAME
    ## @param externalSecrets.serviceaccount.name Name of the service account for External Secrets.
    ##
    name: external-secrets-sa
    
  ## @subsection externalSecrets.clusterSecretStore parameters
  clusterSecretStore:
    ## @param externalSecrets.clusterSecretStore.region AWS Region for AWS Secrets Manager.
    ##
    region: "" # THIS VALUE IS MANDATORY

####################################################
##################### EFS Configs
####################################################

## @section EFS Configs
efsStorageClass:
  ## @param efsStorageClass.enabled Flag to enable EFS Storage Class.
  ##
  enabled: true
  ## @param efsStorageClass.name Name of the EFS Storage Class.
  ##
  name: efs-sc
  ## @param efsStorageClass.reclaimPolicy Reclaim policy for the EFS Storage Class.
  ##
  reclaimPolicy: Retain
  ## @param efsStorageClass.fileSystemId File System ID for the EFS Storage Class.
  ##
  fileSystemId: "" # THIS VALUE IS MANDATORY
  
####################################################
################# Priority Class
####################################################

## @section Priority Class Configurations
priorityClass:
  ## @param priorityClass.enabled Flag to enable Priority Class.
  ##
  enabled: true
  ## @param priorityClass.name Name of the Priority Class.
  ##
  name: high-priority

####################################################
####################### Prometheus
####################################################

## @section Prometheus Configurations
prometheus:
  ## @param prometheus.enabled Flag to enable Prometheus.
  ##
  enabled: true

####################################################
####################### Loki
####################################################

## @section Loki Configurations
loki:
  ## @param loki.enabled Flag to enable Loki.
  ##
  enabled: true

####################################################
####################### Grafana
####################################################

## @section Grafana Configurations
grafana:
  ## @param grafana.enabled Flag to enable Grafana.
  ##
  enabled: true
  ## @param grafana.persistenceSize Persistence size for Grafana.
  ##
  persistenceSize: 10Gi
  ## @param grafana.adminPassword Admin password for Grafana.
  ##
  adminPassword: admin@123
  ## @param grafana.adminUser Admin username for Grafana.
  ##
  adminUser: admin

####################################################
############ Canso Agent Configs
####################################################

## @section cansoAgent configuration
cansoAgent:
  
  ## @param cansoAgent.replicaCount count of replicas
  ##
  replicaCount: 3

  ## @param cansoAgent.enabled Boolean Flag to deploy Canso Agent
  ##
  enabled: true
  ## @param cansoAgent.tolerations Taints that pod can tolerate
  ##
  tolerations: []
  ## @param cansoAgent.affinity Affinity rules for pod scheduling on a node
  ##  
  affinity: {}
  ## @param cansoAgent.roleArn roleArn name of the irsa role for the agent
  ##
  roleArn: "" #THIS VALUE IS MANDATORY
  # roleArn: eks.amazonaws.com/role-arn: arn:aws:iam::AWS_ACCOUNT_ID:role/IAM_ROLE_NAME

####################################################
############ Roles
####################################################

## @section Roles
roles:
  ## @param roles.s3role S3 Role for Canso Agent
  s3role: "" # THIS VALUE IS MANDATORY
  # s3role: eks.amazonaws.com/role-arn: arn:aws:iam::AWS_ACCOUNT_ID:role/IAM_ROLE_NAME
  

####################################################
############ Nginx Ingress Controller
####################################################

## For the official Documentation, see link below
## https://github.com/nginxinc/kubernetes-ingress/blob/main/charts/nginx-ingress/README.md#configuration
ingress:
  ## @param ingress.enabled Boolean Flag to deploy Canso Agent
  ##
  enabled: true
  ## @param ingress.nodeSelector The node selector for pod assignment for the Ingress Controller pods
  ##
  nodeSelector: {}
  ## @param ingress.tolerations The tolerations of the Ingress Controller pods
  ##
  tolerations: []
  ## @param ingress.affinity The affinity of the Ingress Controller pods
  ## 
  affinity: {}
  ## @param ingress.env The additional environment variables to be set on the Ingress Controller pods
  ##
  env: []
  ## @param ingress.auth_pass The basic auth password for the Network Load balancer
  ## Do not Change
  auth_pass: $apr1$IYG9bEux$xw8CgNhoha.oE/xzZcdXR/ # WARNING: CRITICAL VALUE - DO NOT CHANGE

  ## @param ingress.master.enabled Flag for creating ingress controller master
  ##
  master:
    enabled: true

  ## @skip ingress.services The Ingress Controller configuration for canso services
  ##
  services:
  - serviceName: grafana       
    namespace: grafana
    host: "*.com"               
    path: "/grafana/"
    servicePort: 80
    annotations: 
      nginx.org/rewrites: "serviceName=grafana rewrite=/"
  - serviceName: prometheus-server       
    namespace: prometheus
    host: "*.com"               
    path: "/prometheus/"
    servicePort: 80
    annotations: 
      nginx.org/rewrites: "serviceName=prometheus-server rewrite=/"
  - serviceName: argocd-server       
    namespace: argocd
    host: "*.com"               
    path: "/argocd/"
    servicePort: 80
    annotations: 
      nginx.org/rewrites: "serviceName=argocd-server rewrite=/"
  - serviceName: canso-agent       
    namespace: canso-dataplane
    host: "*.com"               
    path: "/canso-agent/"
    servicePort: 80
    annotations: 
      nginx.org/rewrites: "serviceName=canso-agent rewrite=/"
