nameOverride: ""
fullnameOverride: ""

name: task-server
namespace: default
concurrencyPerReplica: 1
replicas: 1


deployment:
  image: shaktimaanbot/canso-task-server:v0.0.1 
  imageSha: ""
  imagePullPolicy: IfNotPresent

broker: "redis://redis-master:6379/0"

serviceAccount:
  create: true
  name: task-server
  annotations: {}

resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 500m
    memory: 512Mi

external_secret:
  enabled: true
  name: docker-secret-cred-task-server
  target_secret_name: docker-secret-cred-task-server
  target_secret_type: kubernetes.io/dockerconfigjson
  target_secret_name_key: .dockerconfigjson
  aws_secret_name: canso/dockerhub
  aws_secret_key: dockerhub

secretStoreRef:
    name: "secretstore-by-role"
    kind: ClusterSecretStore
