####################################################
################ Name Override Configs
####################################################

## @param nameOverride String to override partial name passed in helm install command
##
nameOverride: ""
## @param fullnameOverride String to override full name passed in helm install command
##
fullnameOverride: "task-server"

####################################################
### Default Configs
####################################################

## @param name Name of the server
##
name: task-server
## @param namespace Namespace of the server
##
namespace: default

## @param concurrencyPerReplica Number of tasks to process per replica
##
concurrencyPerReplica: 1

## @param replicas Number of replicas for the task-server deployment
##
replicas: 1

####################################################
### Deployment Configurations
####################################################

deployment:
  ## @section Image Configuration
  image:
    ## @param deployment.image.repository Repository for the image
    ##
    repository: shaktimaanbot/canso-task-server:v0.0.1
    ## @param deployment.image.imageSha SHA256 hash of the image (optional)
    ##
    imageSha: ""
    ## @param deployment.image.pullPolicy Image pull policy for the deployment
    ##
    pullPolicy: Always

## @param broker Connection URL for the message broker
##
broker: "redis://redis-master:6379/0"

####################################################
### Service Account Configurations
####################################################

serviceAccount:
  ## @param serviceAccount.create Bool to enable serviceAccount creation
  ##
  create: true
  ## @param serviceAccount.name Name of the service account
  ##
  name: task-server
  ## @param serviceAccount.annotations Annotations for the service account
  ##
  annotations: {}

####################################################
### Resources Configurations
####################################################

resources:
  ## @section Resource limits configuration
  limits:
    ## @param resources.limits.cpu CPU limits for the task-server container
    ##
    cpu: 1000m
    ## @param resources.limits.memory Memory limits for the task-server container
    ##
    memory: 1024Mi
  ## @section Resource requests configuration
  requests:
    ## @param resources.requests.cpu CPU requests for the task-server container
    ##
    cpu: 500m
    ## @param resources.requests.memory Memory requests for the task-server container
    ##
    memory: 512Mi

####################################################
### External Secret Configurations
####################################################

external_secret:
  ## @param external_secret.enabled Enable external secret
  ##
  enabled: true
  ## @param external_secret.name The name of the secret that will be created
  ##
  name: docker-secret-cred-task-server
  ## @param external_secret.target_secret_name The name of the secret stored in AWS Secrets Manager
  ##
  target_secret_name: docker-secret-cred-task-server
  ## @param external_secret.target_secret_type The type of the secret stored in the external secrets store
  ##
  target_secret_type: kubernetes.io/dockerconfigjson
  ## @param external_secret.target_secret_name_key The key within the secret in the external secrets store that holds the Docker configuration JSON
  ##
  target_secret_name_key: .dockerconfigjson
  ## @param external_secret.aws_secret_name The path to the secret in AWS Secrets Manager that contains the Docker credentials
  ##
  aws_secret_name: canso/dockerhub
  ## @param external_secret.aws_secret_key The key within the secret in AWS Secrets Manager that contains the Docker credentials
  ##
  aws_secret_key: dockerhub

####################################################
### Secret Store Ref Configurations
####################################################

secretStoreRef:
  ## @param secretStoreRef.name Name of the Secret Store resource to fetch the ExternalSecret data
  ##
  name: "secretstore-by-role"
  ## @param secretStoreRef.kind Kind of the SecretStore resource (SecretStore or ClusterSecretStore)
  ##
  kind: ClusterSecretStore
