##############################################################################################
####    Job Details for DB Migrations/Init
##############################################################################################

## @section dbSchemaSetup Job Details for DB Migrations
dbSchemaSetup:
   ## @param dbSchemaSetup.enabled Enable DB schema setup job
   ##
  enabled: true
  
  ## @param dbSchemaSetup.image.repository Image repository for the Flyway migration job
  ## @param dbSchemaSetup.image.tag Image tag for the Flyway migration job
  ## @param dbSchemaSetup.image.pullPolicy Image pull policy for the Flyway migration job
  ##
  image:
    repository: ""
    tag: ""
    pullPolicy: IfNotPresent
  
  ## @param dbSchemaSetup.imagePullSecrets Image pull secrets for the Flyway migration job
  imagePullSecrets: []
  
  ## @param dbSchemaSetup.backoffLimit Job backoff limit
  ##
  backoffLimit: 2

  ## @param dbSchemaSetup.ttlSecondsAfterFinished Job TTL seconds after finished
  ##
  ttlSecondsAfterFinished: 600 # 10 mins

  ## @param dbSchemaSetup.resources Resources (Requests & Limits for memory & CPU) for the migration job
  ##
  ## Example:
  ## resources:
  ##   requests:
  ##     memory: "256Mi"
  ##     cpu: "100m"
  ##   limits:
  ##     memory: "512Mi"
  ##     cpu: "250m"
  ##
  resources:
    requests:
      memory: "768Mi" # Warning - DO NOT REDUCE. Java Heap needs 300MB at-least, flyway image size ~256MB.
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "750m"

## @section rbac RBAC (POD Role & POD Role Bindings)
##
rbac:
  enabled: True


## @section serviceAccount Service Account
## 
serviceAccount:
  ## @param serviceAccount.create Specifies whether a service account should be created
  ##
  create: true
  ## @param serviceAccount.automount Automatically mount a ServiceAccount's API credentials?
  ##
  automount: true
  ## @param serviceAccount.annotations Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  ## @param serviceAccount.name SA Name
  ##
  name: ""


## @skip env Environment variables
env:
  postgresInit:
    # These are used by `pg_isready` to check connection status of a PostgreSQL server
    # as part of the init container.
    PG_HOST: ""  # Postgres Service. Format is usually: "<postgres-release>-postgresql-primary"
    PG_PORT: "5432"
    PG_USER: ""
    PG_DB: ""
    PG_NAMESPACE: "canso-ai-agents"
    PG_SECRET_NAME: "fraud-investigations-db" # Usually Release Name or Full name
    PG_SECRET_KEY: "postgres-password" # CAUTION - DO NOT CHANGE.
  flyway:
    FLYWAY_URL: "" # JDBC URl with format `jdbc:postgresql://<postgres-service-name>.<namespace>.svc.cluster.local:<port>/<database>`
    FLYWAY_USER: "" # Currently same as `env.postgresInit.PG_USER`
    # Flyway locations - https://documentation.red-gate.com/fd/flyway-locations-setting-277579008.html
    # See https://github.com/Yugen-ai/canso-fraud-analyst-service/blob/main/Dockerfile.DBMigrations
    FLYWAY_LOCATIONS: "filesystem:/flyway/sql"
    # Flyway schemas to be used
    FLYWAY_SCHEMAS: "events"
