{{- if .Values.cansoAgent.enabled -}}
{{- if .Values.cansoAgent.clusterRole.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "canso-agent.fullname" . }}
rules:
  - apiGroups: [""]
    resources: ["namespaces", "pods", "resourcequotas", "nodes"]
    verbs: ["list", "watch", "get"]
  - apiGroups: ["apps"]
    resources: ["replicasets", "deployments"]
    verbs: ["list", "watch"]
  - apiGroups: ["argoproj.io"]
    resources: ["applications", "applicationsets", "rollouts"]
    verbs: ["list", "watch"]
{{- end }}
{{- end}}
