{{- if .Values.cansoAgent.enabled -}}
{{- if .Values.cansoAgent.external_secret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.cansoAgent.external_secret.name }}-es
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: {{ .Values.cansoAgent.secretStoreRef.name }}
    kind: {{ .Values.cansoAgent.secretStoreRef.kind }}
  target:
    name: {{ .Values.cansoAgent.external_secret.target_secret_name }}
    template:
      type: {{ .Values.cansoAgent.external_secret.target_secret_type}} 
  data:
  - secretKey: {{ .Values.cansoAgent.external_secret.target_secret_name_key }} 
    remoteRef:
      key: {{ .Values.cansoAgent.external_secret.aws_secret_name }} 
      property: {{ .Values.cansoAgent.external_secret.aws_secret_key }} 
{{- end }}
{{- end}}