{{- if .Values.cansoAgent.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "canso-agent-redis.fullname" . }}
  labels:
    app: {{ include "canso-agent-redis.fullname" . }}
spec:
  ports:
  - port: 6379
    name: {{ include "canso-agent-redis.fullname" . }}
  selector:
    app: {{ include "canso-agent-redis.fullname" . }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "canso-agent-redis.fullname" . }}
  labels:
    app: {{ include "canso-agent-redis.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "canso-agent-redis.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "canso-agent-redis.fullname" . }}
    spec:
      containers:
      - name: {{ include "canso-agent-redis.fullname" . }}
        image: {{ .Values.cansoAgent.redis.image }}
        # https://hub.docker.com/layers/library/redis/7.2.5/images/sha256-f4c27470a48335cd0acca76bbda101aa03e160367bd7494f8ea846c4535f224c?context=explore
        ports:
        - containerPort: 6379
      imagePullSecrets:
        - name: {{ .Values.cansoAgent.external_secret.target_secret_name }}
{{- end}}