{{- if .Values.cansoAgent.enabled -}}
{{- if .Values.cansoAgent.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "canso-agent.serviceAccountName" . }}
  {{- with .Values.cansoAgent.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end}}