{{- if .Values.cansoAgent.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "canso-agent.fullname" . }}
spec:
  type: NodePort
  selector:
    app: {{ include "canso-agent.fullname" . }}
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: {{ .Values.cansoAgent.service.targetport }}
  - name: https
    port: 443
    protocol: TCP
    targetPort: {{ .Values.cansoAgent.service.targetport }}
{{- end}}