{{- if .Values.rbac.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: {{ .Values.db_namespace }}
  name: secrets-reader-binding
  labels:
    {{- include "canso-investigations-db.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "canso-investigations-db.serviceAccountName" . }}
roleRef:
  kind: Role
  name: secrets-reader
  apiGroup: rbac.authorization.k8s.io
{{- end }}