apiVersion: v1
kind: Service
metadata:
  name: {{ include "canso-rule-evaluation-service.name" . }}
  namespace: {{ .Values.namespaceOverride }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.service.targetport }}"
    prometheus.io/path: "/metrics"
    prometheus.io/scheme: "http"
spec:
  type: NodePort
  selector:
    app: {{ include "canso-rule-evaluation-service.name" . }}
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: {{ .Values.service.targetport }}
  - name: https
    port: 443
    protocol: TCP
    targetPort: {{ .Values.service.targetport }}
      