apiVersion: v1
kind: Service
metadata:
  name: fraud-analyst-service
  labels:
    {{- include "canso-fraud-analyst-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "canso-fraud-analyst-service.selectorLabels" . | nindent 4 }}
