name: '[CI/CD] Update README metadata'

on:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'canso-data-plane/**'
jobs:
  update-readme-metadata:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Install readme-generator-for-helm
        run: npm install -g @bitnami/readme-generator-for-helm
      - name: Checkout charts
        uses: actions/checkout@v3
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      - name: Generate READMEs for All Charts
        run: |
          charts_dirs=$(find canso-data-plane -maxdepth 1 -type d)
          for chart in ${charts_dirs}; do
            if [[ -f "${chart}/Chart.yaml" ]]; then # Check if it's a valid chart directory
              echo "Updating README.md for ${chart}"
              readme-generator --values "${chart}/values.yaml" --readme "${chart}/README.md" --schema "/tmp/schema.json"
            fi
          done
          
      - name: Configure Git and push changes
        run: |
            if git status -s | grep canso-data-plane; then
                git config user.name "$GITHUB_ACTOR"
                git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
                git add . && git commit -am "Update README.md with readme-generator-for-helm" --signoff && git push
            fi