apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.openzitiIdentitySecret.name }}-es
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: secretstore-by-role
    kind: ClusterSecretStore
  target:
    name: {{ .Values.openzitiIdentitySecret.name }}
  data:
  - secretKey: {{ .Values.openzitiIdentitySecret.key }} 
    remoteRef:
      key: {{ .Values.openzitiIdentitySecret.cloudProviderSecretName }}